# 监听的域名，会自动过滤不合法的域名
domains = ['as.com', 'cnisx.az'] 
# bark通知的url https://notify.xxxxx.com/ZWQUfXkN3yG25BsV6yVj4o/域名监控服务
bark_url = ""

# Telegram 通知
tg_bot_token = ""
tg_chat_id = ""

# 邮箱通知
smtp_server = 'smtp.example.com'

# 根据服务商提供共的端口，本人测试 126邮箱是465端口
smtp_port = 587
smtp_username = 'your_email@example.com'

# 授权密码, 非邮箱的登陆密码
smtp_password = 'your_email_password'
# 发送到邮箱
recipient_email = 'recipient@example.com'

# 成功发送次数，超过此数则不再通知
max_send_count = 5 
# 检测间隔
check_interval = 120000 

