# 监听的域名，会自动过滤不合法的域名
domains = ['consolog.com', 'cnisx.az', 'nicew.me'] 

# Dynadot API
# 是否开启自动注册（开启后，如果余额充足并且域名可以注册时，将会扣除余额）
auto_register = false
# dynadot_api_key 在 https://www.dynadot.com/zh/account/domain/setting/api.html 获取
dynadot_api_key = ''

# bark通知的url https://notify.xxxxx.com/ZWQUfXkN3yG25BsV6yVj4o/域名监控服务
bark_url = ""

# Telegram 通知
tg_bot_token = ""
tg_chat_id = ""

# 邮箱通知
smtp_server = 'smtp.example.com'

# 根据服务商提供共的端口，本人测试 126邮箱是465端口
smtp_port = 587
smtp_username = 'your_email@example.com'

# 授权密码, 非邮箱的登陆密码
smtp_password = 'auth_password'
# 发送到邮箱
recipient_email = ''

# 成功发送次数，超过此数则不再通知
max_send_count = 5 
# 检测间隔
check_interval = 120000 

